// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbVJxnUNhFz_b95Yw1PZti3HrKK5Y-HRQ',
    appId: '1:264867624855:web:ab8ba52df8ff827e5db6d2',
    messagingSenderId: '264867624855',
    projectId: 'chat-app-283a0',
    authDomain: 'chat-app-283a0.firebaseapp.com',
    storageBucket: 'chat-app-283a0.firebasestorage.app',
    measurementId: 'G-29NPBZGQBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDktTfX_RdbO91TZ68D4I6wU_Z8fzxmPSw',
    appId: '1:264867624855:android:40534392421775815db6d2',
    messagingSenderId: '264867624855',
    projectId: 'chat-app-283a0',
    storageBucket: 'chat-app-283a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw4mum6IRly1higVPLaEfnLob-hzr0DNU',
    appId: '1:264867624855:ios:4ce70b2b74450d045db6d2',
    messagingSenderId: '264867624855',
    projectId: 'chat-app-283a0',
    storageBucket: 'chat-app-283a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw4mum6IRly1higVPLaEfnLob-hzr0DNU',
    appId: '1:264867624855:ios:4ce70b2b74450d045db6d2',
    messagingSenderId: '264867624855',
    projectId: 'chat-app-283a0',
    storageBucket: 'chat-app-283a0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbVJxnUNhFz_b95Yw1PZti3HrKK5Y-HRQ',
    appId: '1:264867624855:web:4e1de8c5d6e26ac35db6d2',
    messagingSenderId: '264867624855',
    projectId: 'chat-app-283a0',
    authDomain: 'chat-app-283a0.firebaseapp.com',
    storageBucket: 'chat-app-283a0.firebasestorage.app',
    measurementId: 'G-34WJH7SJYL',
  );
}
